-- =====================================================================
-- dim_cuaca : dimensi kondisi cuaca (grain = 1 kode cuaca BMKG). SCD Type 1.
-- Catatan snapshot: kode 0 dan 1 sama-sama berlabel "Cerah" -> tetap 2 baris
-- (natural key = kode BMKG, jangan digabung berdasarkan teks).
-- =====================================================================
CREATE TABLE IF NOT EXISTS dim_cuaca (
    cuaca_key     smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- surrogate key
    kode_cuaca    smallint     NOT NULL UNIQUE,      -- natural key (kolom `weather`)
    deskripsi_id  varchar(50)  NOT NULL,             -- weather_desc
    deskripsi_en  varchar(50)  NOT NULL,             -- weather_desc_en
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

INSERT INTO dim_cuaca (cuaca_key, kode_cuaca, deskripsi_id, deskripsi_en)
OVERRIDING SYSTEM VALUE
VALUES (0, -1, 'Tidak diketahui', 'Unknown')
ON CONFLICT (cuaca_key) DO NOTHING;

COMMENT ON TABLE dim_cuaca IS 'Dimensi kondisi cuaca (SCD Type 1, overwrite).';
