-- =====================================================================
-- dim_lokasi : dimensi lokasi (grain = 1 versi desa/kelurahan). SCD TYPE 2.
-- Hierarki didenormalisasi: desa -> kecamatan -> kab/kota -> provinsi
-- (sumber: desa.csv, kecamatan.csv, kabkot.csv, provinsi.csv; kode BPS).
-- =====================================================================
CREATE TABLE IF NOT EXISTS dim_lokasi (
    lokasi_sk      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- surrogate key
    kode_desa       varchar(16)  NOT NULL,          -- natural key (adm4), mis. 73.71.01.1001
    nama_desa       varchar(100) NOT NULL,
    kode_kecamatan  varchar(10)  NOT NULL,
    nama_kecamatan  varchar(100) NOT NULL,
    kode_kabkot     varchar(6)   NOT NULL,
    nama_kabkot     varchar(100) NOT NULL,
    kode_provinsi   varchar(2)   NOT NULL,
    nama_provinsi   varchar(100) NOT NULL,
    -- ---- atribut SCD Type 2 ----
    valid_from      timestamptz  NOT NULL,
    valid_to        timestamptz  NOT NULL DEFAULT '9999-12-31 00:00:00+00',
    is_current      boolean      NOT NULL DEFAULT true,
    row_hash        char(32)     NOT NULL,          -- md5 atribut tracked, deteksi perubahan
    CONSTRAINT ck_lokasi_range   CHECK (valid_to > valid_from),
    CONSTRAINT ck_lokasi_current CHECK (is_current = (valid_to = '9999-12-31 00:00:00+00')),
    CONSTRAINT uq_lokasi_version UNIQUE (kode_desa, valid_from)
);

-- Maks. 1 versi aktif per desa -> cegah baris ganda saat SCD2 dijalankan ulang.
CREATE UNIQUE INDEX IF NOT EXISTS uq_lokasi_current
    ON dim_lokasi (kode_desa) WHERE is_current;

-- Member "Unknown" agar fact tidak kehilangan baris saat lookup gagal.
INSERT INTO dim_lokasi (lokasi_sk, kode_desa, nama_desa, kode_kecamatan, nama_kecamatan,
                        kode_kabkot, nama_kabkot, kode_provinsi, nama_provinsi,
                        valid_from, row_hash)
OVERRIDING SYSTEM VALUE
VALUES (-1, '-', 'Tidak diketahui', '-', 'Tidak diketahui', '-', 'Tidak diketahui',
        '-', 'Tidak diketahui', '1970-01-01', md5('unknown'))
ON CONFLICT (lokasi_sk) DO NOTHING;

COMMENT ON TABLE  dim_lokasi IS 'Dimensi lokasi desa (SCD Type 2). Lookup fact: kode_desa + valid_from <= waktu_utc < valid_to (half-open, jangan BETWEEN).';
COMMENT ON COLUMN dim_lokasi.row_hash IS 'md5(nama_desa|kode_kec|nama_kec|kode_kabkot|nama_kabkot|kode_prov|nama_prov)';
